#! /usr/bin/env python

import sys

from graphviz import Digraph
import yaml


def add_edge(g, out, in_):
    g.edge(out, in_)


def add_node(g, node):
    g.node(node['id'], label=node['name'])


def build(desc, g):
    """Function to take a descriptor and populate a graph."""
    for step in desc['steps']:
        add_node(g, step)
        for e in step.get('upstream', []):
            add_edge(g, e, step['id'])


args = sys.argv[1:]

if len(args) < 1:
  print "Pass at least one yaml file for display"
  sys.exit(1)

for arg in args:
    print "Processing %s..." % arg,
    pipeline = yaml.load(open(arg));
    dot = Digraph(format='pdf')
    build(pipeline, dot)
    dot.render(filename=arg.replace('.yml', '.gv'), view=True)
    print "done"
